modLoader="javafml"
loaderVersion="[26,)"
[[mods]]
modId="lightingwand"
version="${file.jarVersion}"
displayName="Lighting Wand"
authors="Snownee"
displayURL="https://minecraft.curseforge.com/projects/lighting-wand"
description='''Lighting up!

Huge thanks to my supporters:

粉鱼 Lioness131 皮蛋 路人玖 Cherls idyllic_bean 鱼加盐有点咸 洋葱菜菜子 面条公爵 车轮饼 mc00zhu 洛华 纪华裕 可爱至吉 ycccz 东篱下i
'''
