modLoader="javafml"
loaderVersion="[32,)"
[[mods]]
modId="lightingwand"
version="${file.jarVersion}"
displayName="Lighting Wand"
authors="Snownee"
displayURL="https://minecraft.curseforge.com/projects/lighting-wand"
description='''Lighting up!'''
