modLoader="javafml"
loaderVersion="[34,)"
license="MIT"

[[mods]]
modId="lightingwand"
version="${file.jarVersion}"
displayName="Lighting Wand"
authors="Snownee"
displayURL="https://minecraft.curseforge.com/projects/lighting-wand"
description='''Lighting up!'''

[modproperties.lightingwand]
    catalogueItemIcon="lightingwand:wand" #Support for Catalogue mod
